---
dist: xenial
os: linux
language: python
python:
  - "3.6"
env:
  - distribution: centos
    version: 8

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

before_script:
  - chmod 700 tests/test_suite.sh

script:
  - tests/setup_tests.sh /etc/ansible/roles/telegraf-extplugins

after_failure:
  - cat tests/test.log

  #notifications:
    #webhooks: https://galaxy.ansible.com/api/v1/notifications/
