---
## Inspired by https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis
sudo: required

env:
  - distribution: centos
    version: 8

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/telegraf-extplugins:ro ${distribution}-${version}:ansible > "${container_id}"'
  - dscreate -v from-file /etc/ansible/roles/telegraf-extplugins/tests/ldap.inf
  - dsctl example restart

  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/telegraf-extplugins/tests/test.yml -i tests/inventory --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/telegraf-extplugins/tests/test.yml -i tests/inventory'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/telegraf-extplugins/tests/test.yml -i tests/inventory
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker rm -f "$(cat ${container_id})"'

  #notifications:
    #webhooks: https://galaxy.ansible.com/api/v1/notifications/
