FROM centos:8

# Install systemd -- See https://hub.docker.com/_/centos/
RUN dnf -y install systemd systemd-libs
RUN dnf -y update; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*; \
rm -f /etc/systemd/system/*.wants/*; \
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*; \
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN dnf -y install epel-release
RUN dnf -y install git ansible sudo

RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers


# Setup 389ds
RUN dnf -y install 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled powertools
RUN dnf -y module enable 389-ds:1.4
RUN dnf -y install 389-ds-base python3-lib389

# Setup Telegraf
RUN echo $'[influxdb]\n\
name = InfluxDB Repository - RHEL $releasever\n\
baseurl = https://repos.influxdata.com/rhel/$releasever/$basearch/stable\n\
enabled = 1\n\
gpgcheck = 1\n\
gpgkey = https://repos.influxdata.com/influxdb.key\n '\
> /etc/yum.repos.d/influxdb.repo
RUN dnf -y install telegraf

RUN export ANSIBLE_FORCE_COLOR=1

VOLUME ["/sys/fs/cgroup"]

CMD ["/usr/sbin/init"]
